name: publish
on:
  push:
    branches:
      - master
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  publish:
    name: Publish to CDN
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: Brightspace/third-party-actions@actions/checkout
      - name: Setup Node
        uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version: 16.x
      - name: Node Logging
        run: node -v ; npm -v
      - name: Install Dependencies
        run: npm i
      - name: Run Linter and Tests
        run: npm test
      - name: Bundle
        run: npm run bundle-host
      - name: Incremental Release
        id: release
        uses: BrightspaceUI/actions/incremental-release@main
        with:
          GITHUB_TOKEN: ${{ secrets.D2L_GITHUB_TOKEN }}
          DEFAULT_INCREMENT: patch
      - name: Assume role
        uses: Brightspace/third-party-actions@aws-actions/configure-aws-credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          role-to-assume: "arn:aws:iam::771734770799:role/r+Brightspace+frau-jwt+repo"
          role-duration-seconds: 3600
          aws-region: us-east-1
      - name: Publish to CDN
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
        run: npm run publish:cdn
        env:
          GIT_TAG: ${{ steps.release.outputs.VERSION }}
          GIT_COMMIT: ${{ github.sha }}
          AWS_DEFAULT_REGION: us-east-1
